### 모든 카테고리 조회
GET localhost:8200/api/category


### 특정 카테고리 조회
GET localhost:8200/api/category/과일


### 카테고리 생성
POST localhost:8200/api/category
Content-Type: application/json

{
  "categoryName": "장난감"
}


### 특정 카테고리 수정
PUT localhost:8200/api/category/5
Content-Type: application/json

{
  "categoryName": "책"
}


### 특정 카테고리 삭제
DELETE localhost:8200/api/category/5