GET http://localhost:8200/product
Accept: application/json

###

GET http://localhost:8200/product/2
Accept: application/json

###

POST http://localhost:8200/product
Content-Type: application/json

{
  "categoryId": 1,
  "modelNumber": "PPAP",
  "modelName": "파인애플",
  "productImage":"Pineapple.png",
  "unitCost": 18000,
  "description": "이것은 파인애플입니다."
}


###

PUT http://localhost:8200/product/6
Content-Type: application/json

{
  "productId": 6,
  "categoryId": 1,
  "modelNumber": "PPAP",
  "modelName": "파인애플",
  "productImage":"Pineapple.png",
  "unitCost": 1800,
  "description": "파인애플 가격이 떡락했습니다 ㅠㅠ.."
}

###

DELETE http://localhost:8200/product/5