GET http://localhost:8200/api/product?page=0
Accept: application/json

###

GET http://localhost:8200/api/product/1
Accept: application/json
###

GET http://localhost:8200/api/product/

###

POST http://localhost:8200/api/product
Content-Type: application/json

{
  "modelNumber": "DEATH",
  "modelName": "당근칼",
  "productImage":"carrotKnife.png",
  "unitCost": 18000,
  "description": "이것은 당근칼입니다 굉장히 끔찍한 물건이죠"
}


###

PUT http://localhost:8200/api/product/1
Content-Type: application/json

{
  "modelNumber": "DEATH",
  "modelName": "당근칼",
  "productImage":"carrotKnife.png",
  "unitCost": 5000,
  "description": "이것은 흉기가 아닙니다."
}

###

DELETE http://localhost:8200/api/product/5