# 전부 정상작동함 ㅎ

GET localhost:8200/api/user?page=1&size=2
Accept: application/json

###

GET localhost:8200/api/user/myPage
X-USER-ID: jjunho50
Accept: application/json

###

POST localhost:8200/api/user
Content-Type: application/json

{
  "userId": "jjunho50",
  "userName": "정준호",
  "userPassword": "123",
  "userBirth": "19991102"
}


###
PUT http://localhost:8200/api/user
X-USER-ID: jjunho50
Content-Type: application/json

{
  "userId": "jjunho50",
  "userName": "정준호",
  "userPassword": "123",
  "userBirth": "19999999"
}

###

DELETE http://localhost:8200/api/user
X-USER-ID: jjunho50