# 전부 정상작동함 ㅎ

GET http://localhost:8200/api/user
Accept: application/json

###

GET http://localhost:8200/api/user/jjunho50
Accept: application/json

###

GET http://localhost:8200/api/user/jjunho50/review
Accept: application/json

###

POST http://localhost:8200/api/user
Content-Type: application/json

{
  "userId": "fff",
  "userName": "정준호",
  "userPassword": "123",
  "userBirth": "19991102"
}


###
PUT http://localhost:8200/api/user/jjunho50
Content-Type: application/json

{
  "userId": "jjunho50",
  "userName": "정준호",
  "userPassword": "123",
  "userBirth": "19999999"
}

###

DELETE http://localhost:8200/api/user/jjunho50